version: '2.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: merchant
      POSTGRES_PASSWORD: merchant
      POSTGRES_DB: merchant
    restart: always
    ports:
      - 5432:5432
    networks:
      - ch_network      
  merchant:
    image: ivlev/merchant:1
    environment:
      JAVA_OPTS: "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"
      DB_URL: jdbc:postgresql://postgres:5432/merchant
      DB_USER: merchant
      DB_PASS: merchant
    ports:
      - 8080:8080
      - 8000:8000
      - 8443:8443
    networks:
      - ch_network
    depends_on:
      - postgres
networks:
  ch_network:
    driver: bridge      