---
server:
  port: 8443
  ssl:
    key-alias: tomcat
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: 123456
security:
  require-ssl: true  
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/merchant
    username: merchant
    password: merchant
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop    
  tomcat:
    testOnBorrow: true
    validationQuery: "select 1"
    validationInterval: 30000
    removeAbandoned: true
    removeAbandonedTimeout: 60
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000